{% set name = "docxcompose" %}
{% set version = "1.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docxcompose-{{ version }}.tar.gz
  sha256: f91b6e4b136937152081c07471596368324cce2bffa82dfec579f6fa20f59161

build:
  number: 0
  noarch: python
  entry_points:
    - docxcompose = docxcompose.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>3.5
  run:
    - lxml
    - python =2.7|>3.5
    - python-docx >=0.8.8
    - setuptools
    - six

test:
  imports:
    - docxcompose
  commands:
    - pip check
    - docxcompose --help
  requires:
    - pip

about:
  home: https://github.com/4teamwork/docxcompose
  summary: Compose .docx documents
  license: MIT
  # manually package license file. See https://github.com/4teamwork/docxcompose/pull/74
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
