schema_version: 1

context:
  name: docxcompose
  version: "2.1.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docxcompose-${{ version }}.tar.gz
  sha256: 2b19c3fa0a75905832c6518c302ab3a1fd4d41bf5aa58ad677fc83e4052ad7c0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - docxcompose = docxcompose.command:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - python >=${{ python_min }}
    - babel >=2,<3
    - lxml >=5,<6
    - python-docx >=1,<2
    - six >=1,<2

tests:
  - python:
      imports:
        - docxcompose
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - docxcompose --help

about:
  summary: Compose .docx documents
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/4teamwork/docxcompose

extra:
  recipe-maintainers:
    - synapticarbors
